name: day_picker
description: A Flutter widget library which helps us to select days in a week.
version: 2.2.0
homepage: https://github.com/shan-shaji/day_picker

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
